---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Fly Sniper.
--- DateTime: 1/3/2021 2:47 PM
---

local html = "<!DOCTYPE html>" ..
"<html lang=\"en\">" ..
"<head>" ..
    "<meta charset=\"UTF-8\">" ..
    "<title>Wargroove Elo Automatic Entry</title>" ..

    "<script type=\"text/javascript\">" ..
    "var data = JSON.stringify({\"authKey\":\"<playerName>\",\"matchId\":<matchId>,\"victory\":<victory>,\"modApiKey\": \"uEZEyLTRglClnWrie6ObIvo47La5CkDnnFgi18gHrdTxV7n229Sb5EGF3ebEvGjh9ZJ7Ds7FeiIXt4YHYWRk0YuTN2GhcjFAZoA\"});" ..

        "var xhr = new XMLHttpRequest();" ..
        "xhr.withCredentials = true;" ..
        "xhr.addEventListener(\"readystatechange\", function() {" ..
          "if(this.readyState === 4) {" ..
            "var resp = this.responseText;" ..
            "if(resp.includes(\"Error:\")) {" ..
                "alert(resp);" ..
                "window.close();" ..
            "}" ..
            "else {" ..
                "alert(\"Submitted\");" ..
                "console.log(this.responseText);" ..
                "window.close();" ..
            "}" ..
          "}" ..
        "});" ..

        "xhr.open(\"POST\", \"https://groove-of-war-mmr.herokuapp.com/publish\");" ..
        "xhr.setRequestHeader(\"Content-Type\", \"application/json\");" ..

        "xhr.send(data);" ..
    "</script>" ..
"</head>" ..
"<body>" ..
"</body>" ..
"</html>"

return html